Basic structure
mikethreels/react_calculator pull request #1
Opened 2020-11-12 21:51 UTC by mikethreels

## Milestone: Basic file structure 

### When updating the project the following points have been added.
- [x] Used create-react-app to initialize a new React app.
- [x] Deleted all unnecessary files or assets.
- [x] Added prop-types using npm.
- [x] Add big.js using npm.
- [x] Deployed to Heroku.

2020-11-12 22:37 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi @mikethreels :hand: 
Awesome job on this milestone so far. but we have to make some changes before moving on.

- [x] The live link on your README file it's not working right now, We need to make sure that your app is pushed to Heroku or Netlify.
![Screenshot from 2020-11-12 19-36-16](https://user-images.githubusercontent.com/30977845/99004743-5cbbf300-251e-11eb-8ac7-ab96cffc47e4.png)

Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-11-12 22:37 UTC, Torres-ssf commented on src/index.js
> +console.log('hello world');
- [ ] You did a good job deleting all unnecessary files. However, we need to let `src/index.js` file to remain connected with React.

```JS
import React from 'react';
import ReactDOM from 'react-dom';

ReactDOM.render(
  <React.StrictMode>
    <h1>Hello World</h1>
  </React.StrictMode>,
  document.getElementById('root'),
);

```

2020-11-12 22:54 UTC, mikethreels commented
## Milestone: Basic file structure 

### When updating the project the following points have been added.
- [x] Added live link to the readme file
- [x] Added import from React as requested by the TSE

2020-11-13 00:01 UTC, lucasmazo23 approved these changes
## Project approved 🚀
### Great job!
### Your project looks great!
### You can go ahead and merge this pull request!
### Happy coding! 💻
## Lucas Mazo

2020-11-13 00:08 UTC, merged