Event handlers
mikethreels/react_calculator pull request #4
Opened 2020-11-15 22:29 UTC by mikethreels

## Milestone: Calculations

### When updating the project the following points have been added.
- [x] Changed App to a stateful component.
- [x] implemented the handleClick function.
- [x] implemented the onClick event.

2020-11-15 22:57 UTC, kubilaycaglayan requested changes
#### Hello Team 👋
#### Status: Changes Required ♻️

Great job so far! 👏
Click handling is great 👍
Let's cover a few details together to make your project better 😊⏬

### Button Alignment

- [ ] On the top row of number buttons, please fix the order of the numbers. Currently, it goes like 8, 9, 7.

### Behaviour

- [ ] 160 / 2 = and then % throws a prop type warning on the console.

![image](https://user-images.githubusercontent.com/60448833/99199118-ef25f600-27ad-11eb-9b2c-19d0413edbde.png)

- [ ] Consider the edge case, add error handling when the user tries to divide a number by zero. Currently, the application is breaking. 12 / 0 =

## That's it, you can submit another code review request after making these changes ♻️😇

With all my respect 🙏
> Kubilay Caglayan | Technical Support Engineer

2020-11-15 22:57 UTC, kubilaycaglayan commented on src/components/button_panel.jsx
> +        <Button key="7" name="buttongroup2" clickHandler={handleClick} buttonName="7" />
Let's correct the number order. 😊

2020-11-16 17:50 UTC, mikethreels commented
## Milestone: Calculations Update

### When updating the project the following points have been added.
- [x] fixed the order of the buttons.
- [x] fixed the type error when using the % button.
- [x] covered the edge case when divided by 0.

2020-11-16 18:58 UTC, Torres-ssf approved these changes
### Milestone Approved :+1: :clap: 
Hi @mikethreels :hand: 
Awesome job implementing the requested changes :clap: 
Good luck with the next project.

Happy Coding :computer: 
**Sergio Torres**

2020-11-16 19:12 UTC, merged